#!/usr/bin/env python
"""Generate the EXPERIMENT MATRIX configs under ``configs/exp/``.

The experiment matrix is the backbone of the paper: EXP-001..012 walk from the
baseline to the full model, then ablation, robustness, efficiency,
generalization and multi-seed validation. Generating them from one table instead
of hand-writing twelve YAMLs keeps them consistent (same seeds, same schedule,
same dataset) — which is what makes the ablation table a controlled comparison
rather than twelve unrelated runs.

Usage
-----
    python scripts/make_exp_configs.py --dataset ssdd
    python scripts/make_exp_configs.py --dataset sardet100k --scale m --epochs 100
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from saryolo.nn.arch import VARIANTS, variant_filename  # noqa: E402

#: ``(id, model variant, display name, what it isolates)``.
MATRIX: tuple[tuple[str, str, str, str], ...] = (
    ("EXP-001", "baseline", "YOLO baseline", "Engineering baseline; every other row is measured against this."),
    ("EXP-002", "sfe", "+ SAR Feature Enhancement", "Component 1 alone."),
    ("EXP-003", "speckle", "+ Speckle-Aware Module", "Component 2 on top of Component 1."),
    ("EXP-004", "attention", "+ SAR-Adaptive Attention", "Component 3 on top of Components 1-2."),
    ("EXP-005", "amf", "+ Adaptive Multi-Scale Fusion", "Component 4 on top of Components 1-3."),
    ("EXP-006", "p2", "+ P2 small-object head", "High-resolution detection level, justified by dataset stats."),
    ("EXP-007", "full", "FULL SAR-YOLO", "All modules + P2 head + SAR-aware loss."),
    ("EXP-008", "full_noloss", "SAR-YOLO w/o SAR loss", "Isolates the loss (Component 7) from the architecture."),
    ("EXP-009", "full", "Robustness study", "Uses the EXP-007 checkpoint; no separate training is needed."),
    ("EXP-010", "full", "Efficiency study", "Uses the EXP-007 checkpoint; no separate training is needed."),
    ("EXP-011", "full", "Cross-dataset generalization", "Uses the EXP-007 checkpoint; no separate training is needed."),
    ("EXP-012", "full", "Multi-seed validation", "Three seeds for mean +/- std on the headline metric."),
)

#: Experiment ids that are evaluated rather than trained.
EVAL_ONLY = {"EXP-009", "EXP-010", "EXP-011"}


def _write(path: Path, payload: dict, note: str) -> None:
    header = (
        "# GENERATED by scripts/make_exp_configs.py -- edit the generator, not this file.\n"
        f"# {note}\n"
    )
    path.write_text(header + yaml.safe_dump(payload, sort_keys=False))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dataset", default="ssdd", help="Dataset key used for the data config name")
    parser.add_argument("--scale", default="s", choices=["n", "s", "m", "l", "x"], help="Model scale for the matrix")
    parser.add_argument("--epochs", type=int, default=100)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--seeds", nargs="+", type=int, default=[0, 1, 2], help="Seeds for EXP-012")
    parser.add_argument("--models-dir", default="configs/models")
    parser.add_argument("--out", default="configs/exp")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    written, missing = [], []

    for exp_id, variant, name, purpose in MATRIX:
        model_file = Path(args.models_dir) / variant_filename(VARIANTS[variant])
        if not model_file.exists():
            missing.append(str(model_file))
            continue

        rel_model = Path("..") / "models" / model_file.name
        rel_dataset = Path("..") / "datasets" / f"{args.dataset}.yaml"

        train = {
            "epochs": args.epochs,
            "imgsz": args.imgsz,
            "batch": args.batch,
            "seed": args.seeds[0],
            "optimizer": "auto",
            "cos_lr": True,
            "patience": 30,
            "workers": 8,
            "deterministic": True,
        }
        if args.scale in ("m", "l", "x"):
            train["batch"] = max(args.batch // 2, 1)

        payload = {
            "experiment": {"id": exp_id, "name": name, "description": purpose},
            "model": str(rel_model),
            "dataset": str(rel_dataset),
            "train": train,
            "evaluation_only": exp_id in EVAL_ONLY,
            "notes": purpose,
        }
        _write(out / f"{exp_id}_{variant}.yaml", payload, purpose)
        written.append(f"{exp_id}_{variant}.yaml")

    # EXP-012 gets one config per seed so each run is independently traceable.
    for seed in args.seeds[1:]:
        payload = {
            "experiment": {"id": "EXP-012", "name": f"Multi-seed validation (seed {seed})",
                           "description": "Repeat of EXP-007 with a different seed."},
            "model": f"../models/{variant_filename(VARIANTS[f'full_{args.scale}'])}",
            "dataset": f"../datasets/{args.dataset}.yaml",
            "train": {"epochs": args.epochs, "imgsz": args.imgsz, "batch": args.batch, "seed": seed,
                      "cos_lr": True, "patience": 30, "workers": 8, "deterministic": True},
            "notes": f"EXP-007 repeated with seed {seed}; EXP-012 reports mean +/- std over all seeds.",
        }
        _write(out / f"EXP-012_seed{seed}_full_{args.scale}.yaml", payload, f"multi-seed seed {seed}")
        written.append(f"EXP-012_seed{seed}_full_{args.scale}.yaml")

    print(f"wrote {len(written)} configs to {out}")
    for name in written:
        print(f"  {name}")
    if missing:
        print("\nMISSING model YAMLs (run `python -m saryolo arch --variant all` first):")
        for path in sorted(set(missing)):
            print(f"  {path}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
